"use strict";

const ARC_MINUTES_PER_DEGREE = 60,
    ARC_SECONDS_PER_ARC_MINUTE = 60,
    ARC_SECONDS_PER_DEGREE = ARC_MINUTES_PER_DEGREE * ARC_SECONDS_PER_ARC_MINUTE,
    MILLISECONDS_PER_SECOND = 1000,
    RADIANS_PER_DAY = Math.PI * 2,
    SECONDS_PER_MINUTE = 60,
    MINUTES_PER_HOUR = 60,
    SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR,
    HOURS_PER_DAY = 24,
    MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY,
    SECONDS_PER_DAY = SECONDS_PER_MINUTE * MINUTES_PER_DAY,
    MILLISECONDS_PER_DAY = SECONDS_PER_DAY * MILLISECONDS_PER_SECOND,
    EPOCH_MILLIS_AT_2000_01_01_12_00_00 = 946728000000,
    CLOCK_HOURS_PER_SIDEREAL_HOUR = 1 + 1 / (365 + 5 / HOURS_PER_DAY + 48 / MINUTES_PER_DAY + 46 / SECONDS_PER_DAY);

module.exports = {
    ARC_MINUTES_PER_DEGREE,
    ARC_SECONDS_PER_DEGREE,
    MILLISECONDS_PER_SECOND,
    RADIANS_PER_DAY,
    SECONDS_PER_DAY,
    MINUTES_PER_HOUR,
    SECONDS_PER_HOUR,
    EPOCH_MILLIS_AT_2000_01_01_12_00_00,
    MILLISECONDS_PER_DAY
};